version: '3.8'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    mem_limit: 1024m
    mem_reservation: 512m
    cpus: 1
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]